spring:
  application:
    name: servicio-hoteles
server:
  port: 7000  servlet:    context-path: /hoteles  
eureka:
  client:
    service-url:      defaultZone: http://localhost:8761/eureka